"""
OPTIONS ALERT BOT — MAIN SCANNER
==================================
Scans options chains for unusual activity and sends Discord alerts.
Do not edit this file unless you know what you're doing — edit config.py instead.
"""

import csv
import datetime
import json
import time
import traceback
from pathlib import Path
from typing import Optional

import pandas as pd
import pytz
import requests
import yfinance as yf

import config

# ── File paths ─────────────────────────────────────────────────────────────────
BASE_DIR        = Path(__file__).parent
DATA_DIR        = BASE_DIR / "data"
DATA_DIR.mkdir(exist_ok=True)

ALERTS_LOG      = BASE_DIR / "alerts_log.csv"
THRESHOLDS_FILE = DATA_DIR / "thresholds.json"
HISTORY_FILE    = DATA_DIR / "history.json"
BOT_LOG         = BASE_DIR / "bot.log"

ET = pytz.timezone("America/New_York")

# Deduplicate alerts: don't re-fire the same signal within this many minutes
DEDUP_WINDOW_MINUTES = 60

# Track recently fired alerts in memory
_recent_alerts: dict = {}

# Track whether morning analysis ran today
_morning_analysis_done_date: str = ""


# ── Logging ────────────────────────────────────────────────────────────────────

def log(msg: str, level: str = "INFO") -> None:
    ts   = datetime.datetime.now(ET).strftime("%Y-%m-%d %H:%M:%S ET")
    line = f"[{ts}] [{level}] {msg}"
    print(line)
    try:
        with open(BOT_LOG, "a") as f:
            f.write(line + "\n")
    except Exception:
        pass


# ── Threshold helpers ──────────────────────────────────────────────────────────

def load_thresholds() -> dict:
    """Load thresholds from the auto-tuned file, falling back to config defaults."""
    if THRESHOLDS_FILE.exists():
        with open(THRESHOLDS_FILE) as f:
            return json.load(f)
    return config.DEFAULT_THRESHOLDS.copy()


def save_thresholds(thresholds: dict) -> None:
    with open(THRESHOLDS_FILE, "w") as f:
        json.dump(thresholds, f, indent=2)


# ── History helpers ────────────────────────────────────────────────────────────

def load_history() -> dict:
    if HISTORY_FILE.exists():
        with open(HISTORY_FILE) as f:
            return json.load(f)
    return {}


def save_history(history: dict) -> None:
    with open(HISTORY_FILE, "w") as f:
        json.dump(history, f, indent=2)


def _update_history(ticker: str, today_str: str, volume: int, avg_iv: float) -> None:
    """
    Record today's options volume and ATM IV.
    Keeps a rolling 30-day window. Uses the daily MAX volume (accumulates through the day).
    """
    history = load_history()
    if ticker not in history:
        history[ticker] = {"volume": {}, "iv": {}}

    # Keep the highest volume seen today (options volume accumulates during the day)
    existing_vol = history[ticker]["volume"].get(today_str, 0)
    if volume > existing_vol:
        history[ticker]["volume"][today_str] = volume

    # IV: always overwrite with latest reading
    if avg_iv > 0:
        history[ticker]["iv"][today_str] = avg_iv

    # Trim each series to 30 days
    for key in ("volume", "iv"):
        dates = sorted(history[ticker][key].keys())
        for old_date in dates[:-30]:
            del history[ticker][key][old_date]

    save_history(history)


def get_20day_stats(ticker: str) -> tuple:
    """Return (avg_volume, avg_iv, days_of_data) from the last 20 trading days."""
    history = load_history()
    if ticker not in history:
        return None, None, 0

    vols = [v for v in list(history[ticker].get("volume", {}).values())[-20:] if v > 0]
    ivs  = [iv for iv in list(history[ticker].get("iv", {}).values())[-20:] if iv > 0]

    avg_vol = sum(vols) / len(vols) if vols else None
    avg_iv  = sum(ivs)  / len(ivs)  if ivs  else None
    days    = min(len(vols), len(ivs))

    return avg_vol, avg_iv, days


def get_yesterday_iv(ticker: str) -> Optional[float]:
    """Return the most recent prior-day ATM IV reading."""
    history = load_history()
    if ticker not in history:
        return None
    iv_data   = history[ticker].get("iv", {})
    today_str = datetime.datetime.now(ET).strftime("%Y-%m-%d")
    past_dates = sorted(d for d in iv_data if d < today_str)
    return iv_data[past_dates[-1]] if past_dates else None


# ── Options data fetching ──────────────────────────────────────────────────────

def fetch_options_data(ticker: str) -> Optional[dict]:
    """
    Pull the nearest 3 expiration chains from yfinance.
    Returns a dict with volume, IV, put/call ratio, top contract, and stock price.
    Returns None on failure.
    """
    try:
        stock       = yf.Ticker(ticker)
        expirations = stock.options
        if not expirations:
            log(f"{ticker}: no options expirations found", "WARN")
            return None

        # ── Current stock price ──────────────────────────────────────────────
        try:
            current_price = stock.fast_info.last_price
        except Exception:
            hist = stock.history(period="1d")
            if hist.empty:
                log(f"{ticker}: cannot get stock price", "WARN")
                return None
            current_price = float(hist["Close"].iloc[-1])

        if not current_price or current_price <= 0:
            log(f"{ticker}: invalid stock price ({current_price})", "WARN")
            return None

        total_call_vol = 0
        total_put_vol  = 0
        atm_ivs        = []
        top_contract   = None
        top_vol        = 0

        # ── Scan first 3 expirations ─────────────────────────────────────────
        for expiry in expirations[:3]:
            try:
                chain = stock.option_chain(expiry)
                calls = chain.calls.copy()
                puts  = chain.puts.copy()

                for df in (calls, puts):
                    df["volume"]       = df["volume"].fillna(0)
                    df["openInterest"] = df["openInterest"].fillna(0)

                total_call_vol += int(calls["volume"].sum())
                total_put_vol  += int(puts["volume"].sum())

                # ATM = strikes within 5 % of current price
                band = current_price * 0.05
                for df in (calls, puts):
                    atm = df[abs(df["strike"] - current_price) <= band]
                    for iv in atm["impliedVolatility"].dropna():
                        # yfinance returns IV as a decimal (0.35 = 35 %)
                        if 0 < iv < 20:
                            atm_ivs.append(iv * 100)

                # Track the single highest-volume contract across all chains
                all_c = pd.concat(
                    [calls.assign(opt_type="CALL"), puts.assign(opt_type="PUT")],
                    ignore_index=True,
                )
                if not all_c.empty:
                    idx  = all_c["volume"].idxmax()
                    row  = all_c.loc[idx]
                    if row["volume"] > top_vol:
                        top_vol      = row["volume"]
                        iv_raw       = row.get("impliedVolatility", 0)
                        top_contract = {
                            "symbol": row.get("contractSymbol", "N/A"),
                            "type":   row["opt_type"],
                            "strike": row["strike"],
                            "expiry": expiry,
                            "volume": int(row["volume"]),
                            "oi":     int(row["openInterest"]),
                            "iv":     round(iv_raw * 100, 1) if pd.notna(iv_raw) else 0,
                            "last":   round(row.get("lastPrice", 0), 2),
                        }
            except Exception as exc:
                log(f"{ticker} ({expiry}): chain error — {exc}", "WARN")
                continue

        total_volume  = total_call_vol + total_put_vol
        avg_iv        = round(sum(atm_ivs) / len(atm_ivs), 1) if atm_ivs else 0.0
        put_call_ratio = round(total_put_vol / total_call_vol, 2) if total_call_vol > 0 else 0.0

        return {
            "ticker":         ticker,
            "current_price":  round(current_price, 2),
            "total_volume":   total_volume,
            "call_volume":    total_call_vol,
            "put_volume":     total_put_vol,
            "put_call_ratio": put_call_ratio,
            "avg_iv":         avg_iv,
            "top_contract":   top_contract,
            "timestamp":      datetime.datetime.now(ET).isoformat(),
        }

    except Exception as exc:
        log(f"{ticker}: unexpected error — {exc}", "ERROR")
        traceback.print_exc()
        return None


# ── Signal detection ───────────────────────────────────────────────────────────

def check_signals(data: dict, thresholds: dict) -> list:
    """
    Compare current options snapshot against thresholds.
    Returns a list of triggered signal dicts (may be empty).
    Also updates the rolling history file.
    """
    ticker    = data["ticker"]
    today_str = datetime.datetime.now(ET).strftime("%Y-%m-%d")
    signals   = []

    avg_vol_20d, _, days_data = get_20day_stats(ticker)
    yesterday_iv              = get_yesterday_iv(ticker)

    # ── 1. Volume spike ──────────────────────────────────────────────────────
    if avg_vol_20d and avg_vol_20d > 0:
        ratio = data["total_volume"] / avg_vol_20d
        if ratio >= thresholds["volume_spike_multiplier"]:
            signals.append({
                "type":        "volume_spike",
                "label":       "Options Volume Spike",
                "value":       round(ratio, 2),
                "threshold":   thresholds["volume_spike_multiplier"],
                "description": f"{ratio:.1f}x the {days_data}-day average volume",
                "confidence":  _conf_volume(ratio, thresholds["volume_spike_multiplier"]),
            })
    else:
        if days_data < 5:
            log(f"{ticker}: only {days_data} day(s) of volume history — need 5+ for spike signal")

    # ── 2. IV jump ───────────────────────────────────────────────────────────
    if yesterday_iv and yesterday_iv > 0 and data["avg_iv"] > 0:
        iv_chg = ((data["avg_iv"] - yesterday_iv) / yesterday_iv) * 100
        if iv_chg >= thresholds["iv_jump_percent"]:
            signals.append({
                "type":        "iv_jump",
                "label":       "Implied Volatility Spike",
                "value":       round(iv_chg, 1),
                "threshold":   thresholds["iv_jump_percent"],
                "description": (
                    f"ATM IV jumped {iv_chg:.1f}% "
                    f"({yesterday_iv:.1f}% → {data['avg_iv']:.1f}%)"
                ),
                "confidence":  _conf_iv(iv_chg, thresholds["iv_jump_percent"]),
            })

    # ── 3. Put/call skew ─────────────────────────────────────────────────────
    pc = data["put_call_ratio"]
    if pc > 0:
        if pc >= thresholds["put_call_ratio_high"]:
            signals.append({
                "type":        "put_call_high",
                "label":       "Bearish Put/Call Skew",
                "value":       pc,
                "threshold":   thresholds["put_call_ratio_high"],
                "description": (
                    f"Put/Call ratio {pc:.2f} — heavy put buying "
                    f"(threshold {thresholds['put_call_ratio_high']})"
                ),
                "confidence":  _conf_pc(pc, thresholds["put_call_ratio_high"], "high"),
            })
        elif pc <= thresholds["put_call_ratio_low"]:
            signals.append({
                "type":        "put_call_low",
                "label":       "Bullish Put/Call Skew",
                "value":       pc,
                "threshold":   thresholds["put_call_ratio_low"],
                "description": (
                    f"Put/Call ratio {pc:.2f} — heavy call buying "
                    f"(threshold {thresholds['put_call_ratio_low']})"
                ),
                "confidence":  _conf_pc(pc, thresholds["put_call_ratio_low"], "low"),
            })

    # ── Update rolling history ────────────────────────────────────────────────
    _update_history(ticker, today_str, data["total_volume"], data["avg_iv"])

    return signals


# ── Confidence scoring ─────────────────────────────────────────────────────────

def _conf_volume(ratio: float, threshold: float) -> int:
    excess = (ratio - threshold) / threshold   # 0 = just at threshold
    return min(100, int(50 + min(45, excess * 45)))

def _conf_iv(change_pct: float, threshold: float) -> int:
    excess = (change_pct - threshold) / threshold
    return min(100, int(50 + min(45, excess * 45)))

def _conf_pc(pc: float, threshold: float, direction: str) -> int:
    if direction == "high":
        excess = (pc - threshold) / threshold
    else:
        excess = (threshold - pc) / threshold
    return min(100, int(50 + min(45, excess * 45)))


# ── Deduplication ─────────────────────────────────────────────────────────────

def _is_duplicate(ticker: str, signal_type: str) -> bool:
    key = f"{ticker}:{signal_type}"
    last_fired = _recent_alerts.get(key)
    if last_fired:
        elapsed = (datetime.datetime.now(ET) - last_fired).total_seconds() / 60
        if elapsed < DEDUP_WINDOW_MINUTES:
            return True
    _recent_alerts[key] = datetime.datetime.now(ET)
    return False


# ── Discord alert delivery ─────────────────────────────────────────────────────

def _confidence_bar(score: int) -> str:
    filled = score // 10
    return "█" * filled + "░" * (10 - filled) + f"  {score}/100"

def send_discord_alert(data: dict, signal: dict) -> bool:
    """POST a rich embed to the Discord webhook. Falls back to console if not configured."""
    webhook_url = config.DISCORD_WEBHOOK_URL

    if not webhook_url or webhook_url == "YOUR_DISCORD_WEBHOOK_URL_HERE":
        _print_console_alert(data, signal)
        return True

    sig_type = signal["type"]
    if "put_call_high" in sig_type:
        color = 0xE74C3C   # red
    elif "put_call_low" in sig_type:
        color = 0x2ECC71   # green
    elif "volume" in sig_type:
        color = 0xF39C12   # orange
    else:
        color = 0x9B59B6   # purple

    fields = [
        {"name": "Signal Type",   "value": signal["label"],              "inline": True},
        {"name": "Stock Price",   "value": f"${data['current_price']}",  "inline": True},
        {"name": "Confidence",    "value": _confidence_bar(signal["confidence"]), "inline": False},
        {"name": "Details",       "value": signal["description"],         "inline": False},
        {"name": "ATM IV",        "value": f"{data['avg_iv']}%",          "inline": True},
        {"name": "Put/Call",      "value": str(data["put_call_ratio"]),   "inline": True},
        {"name": "Total Vol",     "value": f"{data['total_volume']:,}",   "inline": True},
    ]

    if data.get("top_contract"):
        c   = data["top_contract"]
        val = (
            f"**{c['type']}**  |  Strike: ${c['strike']}  |  Exp: {c['expiry']}\n"
            f"Volume: {c['volume']:,}  |  OI: {c['oi']:,}  |  IV: {c['iv']}%  |  Last: ${c['last']}"
        )
        fields.append({"name": "Hottest Contract", "value": val, "inline": False})

    payload = {
        "embeds": [{
            "title":     f"Options Alert — {data['ticker']}",
            "color":     color,
            "fields":    fields,
            "footer":    {"text": "Options Alert Bot  •  self-improving"},
            "timestamp": datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
        }]
    }

    try:
        resp = requests.post(webhook_url, json=payload, timeout=10)
        if resp.status_code in (200, 204):
            log(f"Discord alert sent: {data['ticker']} — {signal['label']}")
            return True
        log(f"Discord error {resp.status_code}: {resp.text[:200]}", "ERROR")
        return False
    except Exception as exc:
        log(f"Discord request failed: {exc}", "ERROR")
        return False


def send_health_alert(message: str, alerts_fired: int, tickers_scanned: int) -> None:
    """Post a scan-summary embed to the health Discord channel (if configured)."""
    webhook_url = getattr(config, "DISCORD_HEALTH_WEBHOOK_URL", "")
    if not webhook_url:
        return
    now = datetime.datetime.now(ET).strftime("%Y-%m-%d %H:%M ET")
    payload = {
        "embeds": [{
            "title": "Bot Health Update",
            "color": 0x3498DB,
            "fields": [
                {"name": "Time",             "value": now,                  "inline": True},
                {"name": "Tickers Scanned",  "value": str(tickers_scanned), "inline": True},
                {"name": "Alerts Fired",     "value": str(alerts_fired),    "inline": True},
                {"name": "Status",           "value": message,              "inline": False},
            ],
            "footer": {"text": "Options Alert Bot — Health Monitor"},
        }]
    }
    try:
        resp = requests.post(webhook_url, json=payload, timeout=10)
        if resp.status_code not in (200, 204):
            log(f"Health Discord error {resp.status_code}", "WARN")
    except Exception as exc:
        log(f"Health Discord request failed: {exc}", "WARN")


def _print_console_alert(data: dict, signal: dict) -> None:
    sep = "=" * 58
    print(f"\n{sep}")
    print(f"  ALERT: {data['ticker']}  —  {signal['label']}")
    print(f"  {signal['description']}")
    print(f"  Stock price : ${data['current_price']}")
    print(f"  Confidence  : {_confidence_bar(signal['confidence'])}")
    if data.get("top_contract"):
        c = data["top_contract"]
        print(
            f"  Hot contract: {c['type']} ${c['strike']} "
            f"({c['expiry']})  Vol:{c['volume']:,}  IV:{c['iv']}%"
        )
    print(f"{sep}\n")


# ── Alert CSV logging ──────────────────────────────────────────────────────────

_CSV_HEADERS = [
    "timestamp", "ticker", "signal_type", "signal_label",
    "signal_value", "threshold_used", "price_at_alert",
    "put_call_ratio", "avg_iv", "total_volume",
    "top_contract", "confidence_score", "outcome",
]


def ensure_log_file() -> None:
    if not ALERTS_LOG.exists():
        with open(ALERTS_LOG, "w", newline="") as f:
            csv.DictWriter(f, fieldnames=_CSV_HEADERS).writeheader()
        log(f"Created alerts log at {ALERTS_LOG}")


def log_alert(data: dict, signal: dict) -> None:
    """Append one row to the CSV alert log."""
    ensure_log_file()
    c_str = ""
    if data.get("top_contract"):
        c = data["top_contract"]
        c_str = f"{c['type']} ${c['strike']} {c['expiry']} Vol:{c['volume']:,}"

    row = {
        "timestamp":       datetime.datetime.now(ET).strftime("%Y-%m-%d %H:%M:%S"),
        "ticker":          data["ticker"],
        "signal_type":     signal["type"],
        "signal_label":    signal["label"],
        "signal_value":    signal["value"],
        "threshold_used":  signal["threshold"],
        "price_at_alert":  data["current_price"],
        "put_call_ratio":  data["put_call_ratio"],
        "avg_iv":          data["avg_iv"],
        "total_volume":    data["total_volume"],
        "top_contract":    c_str,
        "confidence_score": signal["confidence"],
        "outcome":         "",   # ← you fill this in: 1 = correct, 0 = wrong
    }
    with open(ALERTS_LOG, "a", newline="") as f:
        csv.DictWriter(f, fieldnames=_CSV_HEADERS).writerow(row)


# ── Market hours ───────────────────────────────────────────────────────────────

def is_market_hours() -> bool:
    """True if NYSE is currently open (Mon–Fri, 9:30am–4:00pm ET)."""
    now = datetime.datetime.now(ET)
    if now.weekday() >= 5:
        return False
    market_open  = now.replace(hour=9,  minute=30, second=0, microsecond=0)
    market_close = now.replace(hour=16, minute=0,  second=0, microsecond=0)
    return market_open <= now < market_close


def is_pre_market_window() -> bool:
    """True between 8:00–9:25am ET on weekdays (morning analysis window)."""
    now = datetime.datetime.now(ET)
    if now.weekday() >= 5:
        return False
    start = now.replace(hour=8,  minute=0,  second=0, microsecond=0)
    end   = now.replace(hour=9,  minute=25, second=0, microsecond=0)
    return start <= now < end


# ── Main scan loop ─────────────────────────────────────────────────────────────

def run_scan() -> None:
    thresholds = load_thresholds()
    log(f"Scanning {len(config.TICKERS)} ticker(s): {', '.join(config.TICKERS)}")

    alerts_fired = 0
    for ticker in config.TICKERS:
        log(f"  Checking {ticker} ...")
        data = fetch_options_data(ticker)
        if not data:
            continue

        signals = check_signals(data, thresholds)

        if not signals:
            log(
                f"  {ticker}: no signals  "
                f"(PC={data['put_call_ratio']}, IV={data['avg_iv']}%, "
                f"Vol={data['total_volume']:,})"
            )

        for sig in signals:
            if _is_duplicate(ticker, sig["type"]):
                log(f"  {ticker}: duplicate {sig['type']} suppressed (fired < {DEDUP_WINDOW_MINUTES} min ago)")
                continue
            log(f"  *** SIGNAL: {ticker} — {sig['label']} (confidence {sig['confidence']}/100) ***")
            send_discord_alert(data, sig)
            log_alert(data, sig)
            alerts_fired += 1

        time.sleep(1.5)   # Polite pause between tickers

    log(f"Scan complete — {alerts_fired} alert(s) sent.")
    send_health_alert(
        f"Scan complete — {alerts_fired} alert(s) fired across {len(config.TICKERS)} tickers",
        alerts_fired,
        len(config.TICKERS),
    )


def main() -> None:
    global _morning_analysis_done_date

    log("=" * 60)
    log("Options Alert Bot starting")
    log(f"Tickers  : {', '.join(config.TICKERS)}")
    log(f"Interval : {config.SCAN_INTERVAL_MINUTES} min during market hours (9:30am–4pm ET)")
    log("=" * 60)

    ensure_log_file()

    if config.DISCORD_WEBHOOK_URL == "YOUR_DISCORD_WEBHOOK_URL_HERE":
        log("NOTE: Discord webhook not set — alerts will print here instead.", "WARN")
        log("Edit config.py and add your webhook URL to send real Discord alerts.", "WARN")

    while True:
        now       = datetime.datetime.now(ET)
        today_str = now.strftime("%Y-%m-%d")

        # Morning self-improvement (once per weekday, pre-market)
        if is_pre_market_window() and _morning_analysis_done_date != today_str:
            try:
                from self_improve import run_morning_analysis
                run_morning_analysis()
                _morning_analysis_done_date = today_str
            except Exception as exc:
                log(f"Morning analysis failed: {exc}", "ERROR")

        # Market-hours scan
        if is_market_hours():
            try:
                run_scan()
            except Exception as exc:
                log(f"Scan error: {exc}", "ERROR")
                traceback.print_exc()
        else:
            log(
                f"Market closed ({now.strftime('%A %H:%M')} ET). "
                f"Next check in {config.SCAN_INTERVAL_MINUTES} min."
            )

        time.sleep(config.SCAN_INTERVAL_MINUTES * 60)


if __name__ == "__main__":
    main()
