"""
OPTIONS ALERT BOT — MAIN SCANNER v2
======================================
Scans options chains for unusual activity.
STRICT SILENCE RULE: Only fires when all four gates pass.
A scan with zero alerts because nothing qualified is a SUCCESS.

Do not edit this file — edit config.py instead.
"""

import csv
import datetime
import json
import time
import traceback
from pathlib import Path
from typing import Optional

import pandas as pd
import pytz
import requests
import yfinance as yf

import config
import data_sources
from earnings_calendar import is_earnings_play, earnings_in_next_week
from signal_filter import check_all_gates
from news_sentiment import build_context_summary

# ── Paths ───────────────────────────────────────────────────────────────────────
BASE_DIR        = Path(__file__).parent
DATA_DIR        = BASE_DIR / "data"
DATA_DIR.mkdir(exist_ok=True)

ALERTS_LOG      = BASE_DIR / "alerts_log.csv"
THRESHOLDS_FILE = DATA_DIR / "thresholds.json"
HISTORY_FILE    = DATA_DIR / "history.json"
BOT_LOG         = BASE_DIR / "bot.log"

ET = pytz.timezone("America/New_York")

DEDUP_WINDOW_MINUTES = 60
_recent_alerts: dict = {}
_morning_analysis_done_date: str = ""


# ── Logging ─────────────────────────────────────────────────────────────────────

def log(msg: str, level: str = "INFO") -> None:
    ts   = datetime.datetime.now(ET).strftime("%Y-%m-%d %H:%M:%S ET")
    line = f"[{ts}] [{level}] {msg}"
    print(line)
    try:
        with open(BOT_LOG, "a") as f:
            f.write(line + "\n")
    except Exception:
        pass


# ── Thresholds ──────────────────────────────────────────────────────────────────

def load_thresholds() -> dict:
    if THRESHOLDS_FILE.exists():
        with open(THRESHOLDS_FILE) as f:
            return json.load(f)
    return config.DEFAULT_THRESHOLDS.copy()


def save_thresholds(t: dict) -> None:
    with open(THRESHOLDS_FILE, "w") as f:
        json.dump(t, f, indent=2)


# ── Rolling history ─────────────────────────────────────────────────────────────

def load_history() -> dict:
    if HISTORY_FILE.exists():
        with open(HISTORY_FILE) as f:
            return json.load(f)
    return {}


def save_history(h: dict) -> None:
    with open(HISTORY_FILE, "w") as f:
        json.dump(h, f, indent=2)


def _update_history(ticker: str, today_str: str, volume: int, avg_iv: float) -> None:
    h = load_history()
    if ticker not in h:
        h[ticker] = {"volume": {}, "iv": {}}

    existing = h[ticker]["volume"].get(today_str, 0)
    if volume > existing:
        h[ticker]["volume"][today_str] = volume

    if avg_iv > 0:
        h[ticker]["iv"][today_str] = avg_iv

    for key in ("volume", "iv"):
        dates = sorted(h[ticker][key].keys())
        for old in dates[:-30]:
            del h[ticker][key][old]

    save_history(h)


def get_20day_stats(ticker: str):
    h = load_history()
    if ticker not in h:
        return None, None, 0
    vols = [v for v in list(h[ticker].get("volume", {}).values())[-20:] if v > 0]
    ivs  = [i for i in list(h[ticker].get("iv", {}).values())[-20:] if i > 0]
    avg_vol = sum(vols) / len(vols) if vols else None
    avg_iv  = sum(ivs)  / len(ivs)  if ivs  else None
    return avg_vol, avg_iv, min(len(vols), len(ivs))


def get_yesterday_iv(ticker: str) -> Optional[float]:
    h = load_history()
    if ticker not in h:
        return None
    iv_data   = h[ticker].get("iv", {})
    today_str = datetime.datetime.now(ET).strftime("%Y-%m-%d")
    past      = sorted(d for d in iv_data if d < today_str)
    return iv_data[past[-1]] if past else None


# ── Options data fetching ───────────────────────────────────────────────────────

def fetch_options_data(ticker: str) -> Optional[dict]:
    """
    Pull options chain data. Tries Robinhood first, falls back to yfinance.
    Returns None on failure.
    """
    try:
        current_price = data_sources.get_current_price(ticker)
        if not current_price or current_price <= 0:
            log(f"{ticker}: cannot get stock price", "WARN")
            return None

        chain_data = data_sources.get_options_chain(ticker, num_expirations=3)
        if not chain_data:
            log(f"{ticker}: no options chain data", "WARN")
            return None

        source         = chain_data.get("source", "yfinance")
        total_call_vol = 0
        total_put_vol  = 0
        atm_ivs        = []
        top_contract   = None
        top_vol        = 0

        for exp_block in chain_data.get("expirations", []):
            expiry = exp_block["expiry"]
            calls  = exp_block["calls"].copy()
            puts   = exp_block["puts"].copy()

            for df in (calls, puts):
                df["volume"]       = pd.to_numeric(df.get("volume", 0), errors="coerce").fillna(0)
                df["openInterest"] = pd.to_numeric(df.get("openInterest", 0), errors="coerce").fillna(0)

            total_call_vol += int(calls["volume"].sum())
            total_put_vol  += int(puts["volume"].sum())

            band = current_price * 0.05
            for df in (calls, puts):
                atm = df[abs(df["strike"] - current_price) <= band]
                for iv in atm["impliedVolatility"].dropna():
                    if 0 < iv < 20:
                        atm_ivs.append(iv * 100)

            all_c = pd.concat(
                [calls.assign(opt_type="CALL"), puts.assign(opt_type="PUT")],
                ignore_index=True,
            )
            if not all_c.empty and all_c["volume"].max() > 0:
                idx = all_c["volume"].idxmax()
                row = all_c.loc[idx]
                if row["volume"] > top_vol:
                    top_vol    = row["volume"]
                    iv_raw     = row.get("impliedVolatility", 0)
                    top_contract = {
                        "symbol": row.get("contractSymbol", "N/A"),
                        "type":   row["opt_type"],
                        "strike": row["strike"],
                        "expiry": expiry,
                        "volume": int(row["volume"]),
                        "oi":     int(row["openInterest"]),
                        "iv":     round(iv_raw * 100, 1) if pd.notna(iv_raw) else 0,
                        "last":   round(row.get("lastPrice", 0), 2),
                    }

        total_volume   = total_call_vol + total_put_vol
        avg_iv         = round(sum(atm_ivs) / len(atm_ivs), 1) if atm_ivs else 0.0
        put_call_ratio = round(total_put_vol / total_call_vol, 2) if total_call_vol > 0 else 0.0

        return {
            "ticker":         ticker,
            "current_price":  round(current_price, 2),
            "total_volume":   total_volume,
            "call_volume":    total_call_vol,
            "put_volume":     total_put_vol,
            "put_call_ratio": put_call_ratio,
            "avg_iv":         avg_iv,
            "top_contract":   top_contract,
            "data_source":    source,
            "timestamp":      datetime.datetime.now(ET).isoformat(),
        }

    except Exception as exc:
        log(f"{ticker}: fetch error — {exc}", "ERROR")
        traceback.print_exc()
        return None


# ── Raw signal detection ────────────────────────────────────────────────────────

def detect_raw_signals(data: dict, thresholds: dict) -> list:
    """
    Detect raw signals against thresholds.
    These are CANDIDATES only — they must still pass all four gates.
    Also updates rolling history.
    """
    ticker    = data["ticker"]
    today_str = datetime.datetime.now(ET).strftime("%Y-%m-%d")
    signals   = []

    avg_vol_20d, _, days_data = get_20day_stats(ticker)
    yesterday_iv              = get_yesterday_iv(ticker)

    # Volume spike
    if avg_vol_20d and avg_vol_20d > 0:
        ratio = data["total_volume"] / avg_vol_20d
        if ratio >= thresholds["volume_spike_multiplier"]:
            signals.append({
                "type":         "volume_spike",
                "label":        "Options Volume Spike",
                "value":        round(ratio, 2),
                "volume_ratio": round(ratio, 2),
                "threshold":    thresholds["volume_spike_multiplier"],
                "description":  f"{ratio:.1f}x the {days_data}-day average volume",
                "iv_change":    None,
                "pc_ratio":     data["put_call_ratio"],
            })
    elif days_data < 5:
        log(f"{ticker}: only {days_data} day(s) of volume history — building baseline")

    # IV jump
    if yesterday_iv and yesterday_iv > 0 and data["avg_iv"] > 0:
        iv_chg = ((data["avg_iv"] - yesterday_iv) / yesterday_iv) * 100
        if iv_chg >= thresholds["iv_jump_percent"]:
            avg_vol_20d_val = avg_vol_20d or 1
            ratio = data["total_volume"] / avg_vol_20d_val
            signals.append({
                "type":         "iv_jump",
                "label":        "Implied Volatility Spike",
                "value":        round(iv_chg, 1),
                "volume_ratio": round(ratio, 2),
                "threshold":    thresholds["iv_jump_percent"],
                "description":  (
                    f"ATM IV jumped {iv_chg:.1f}% "
                    f"({yesterday_iv:.1f}% → {data['avg_iv']:.1f}%)"
                ),
                "iv_change":   round(iv_chg, 1),
                "pc_ratio":    data["put_call_ratio"],
            })

    # Put/call skew
    pc = data["put_call_ratio"]
    avg_vol_20d_val = avg_vol_20d or 1
    ratio = data["total_volume"] / avg_vol_20d_val
    if pc > 0:
        if pc >= thresholds["put_call_ratio_high"]:
            signals.append({
                "type":         "put_call_high",
                "label":        "Bearish Put/Call Skew",
                "value":        pc,
                "volume_ratio": round(ratio, 2),
                "threshold":    thresholds["put_call_ratio_high"],
                "description":  (
                    f"Put/Call ratio {pc:.2f} — heavy put buying "
                    f"(threshold: {thresholds['put_call_ratio_high']})"
                ),
                "iv_change":   None,
                "pc_ratio":    pc,
            })
        elif pc <= thresholds["put_call_ratio_low"]:
            signals.append({
                "type":         "put_call_low",
                "label":        "Bullish Put/Call Skew",
                "value":        pc,
                "volume_ratio": round(ratio, 2),
                "threshold":    thresholds["put_call_ratio_low"],
                "description":  (
                    f"Put/Call ratio {pc:.2f} — heavy call buying "
                    f"(threshold: {thresholds['put_call_ratio_low']})"
                ),
                "iv_change":   None,
                "pc_ratio":    pc,
            })

    _update_history(ticker, today_str, data["total_volume"], data["avg_iv"])
    return signals


# ── Deduplication ───────────────────────────────────────────────────────────────

def _is_duplicate(ticker: str, signal_type: str) -> bool:
    key        = f"{ticker}:{signal_type}"
    last_fired = _recent_alerts.get(key)
    if last_fired:
        elapsed = (datetime.datetime.now(ET) - last_fired).total_seconds() / 60
        if elapsed < DEDUP_WINDOW_MINUTES:
            return True
    _recent_alerts[key] = datetime.datetime.now(ET)
    return False


# ── Discord delivery ────────────────────────────────────────────────────────────

def _confidence_bar(score: int) -> str:
    filled = score // 10
    return "█" * filled + "░" * (10 - filled) + f"  {score}/100"


def send_discord_alert(
    data: dict,
    signal: dict,
    confidence: int,
    is_ep: bool,
    earnings_date: Optional[object],
    context: str,
) -> bool:
    webhook = config.DISCORD_WEBHOOK_URL
    if not webhook or webhook == "YOUR_DISCORD_WEBHOOK_URL_HERE":
        _print_console_alert(data, signal, confidence, context)
        return True

    sig_type = signal["type"]
    if "put_call_high" in sig_type:
        color = 0xE74C3C     # red — bearish
    elif "put_call_low" in sig_type:
        color = 0x2ECC71     # green — bullish
    elif "volume" in sig_type:
        color = 0xF39C12     # orange — unusual activity
    else:
        color = 0x9B59B6     # purple — IV

    ep_label = ""
    if is_ep and earnings_date:
        ep_label = f"  🎰 EARNINGS PLAY — reports {earnings_date}"
    elif earnings_date:
        ep_label = f"  📅 Earnings: {earnings_date}"

    title = f"🚨 Options Alert — {data['ticker']}{ep_label}"

    fields = [
        {"name": "Signal",        "value": signal["label"],                "inline": True},
        {"name": "Stock Price",   "value": f"${data['current_price']}",    "inline": True},
        {"name": "Data Source",   "value": data.get("data_source", "yfinance"), "inline": True},
        {"name": "Confidence",    "value": _confidence_bar(confidence),    "inline": False},
        {"name": "Details",       "value": signal["description"],          "inline": False},
        {"name": "ATM IV",        "value": f"{data['avg_iv']}%",           "inline": True},
        {"name": "Put/Call",      "value": str(data["put_call_ratio"]),    "inline": True},
        {"name": "Total Options Vol", "value": f"{data['total_volume']:,}", "inline": True},
    ]

    if data.get("top_contract"):
        c   = data["top_contract"]
        val = (
            f"**{c['type']}**  |  Strike: ${c['strike']}  |  Exp: {c['expiry']}\n"
            f"Volume: {c['volume']:,}  |  OI: {c['oi']:,}  |  IV: {c['iv']}%  |  Last: ${c['last']}"
        )
        fields.append({"name": "🔥 Hottest Contract", "value": val, "inline": False})

    if context:
        fields.append({"name": "📰 Context", "value": context[:1024], "inline": False})

    payload = {
        "embeds": [{
            "title":     title,
            "color":     color,
            "fields":    fields,
            "footer":    {"text": "Options Bot v2 — selective & disciplined"},
            "timestamp": datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
        }]
    }

    try:
        resp = requests.post(webhook, json=payload, timeout=10)
        if resp.status_code in (200, 204):
            log(f"Discord alert sent: {data['ticker']} — {signal['label']} (confidence {confidence})")
            return True
        log(f"Discord error {resp.status_code}: {resp.text[:200]}", "ERROR")
        return False
    except Exception as exc:
        log(f"Discord request failed: {exc}", "ERROR")
        return False


def send_health_update(message: str, alerts_fired: int, tickers_scanned: int,
                       silent_reasons: list) -> None:
    webhook = getattr(config, "DISCORD_HEALTH_WEBHOOK_URL", "")
    if not webhook:
        return

    now = datetime.datetime.now(ET).strftime("%Y-%m-%d %H:%M ET")

    silent_str = (
        "\n".join(f"• {r}" for r in silent_reasons[-5:])
        if silent_reasons
        else "All tickers — nothing qualified"
    )

    payload = {
        "embeds": [{
            "title": "⚙️ Scan Complete",
            "color": 0x3498DB if alerts_fired > 0 else 0x95A5A6,
            "fields": [
                {"name": "Time",            "value": now,                  "inline": True},
                {"name": "Scanned",         "value": str(tickers_scanned), "inline": True},
                {"name": "Alerts Fired",    "value": str(alerts_fired),    "inline": True},
                {"name": "Silent (filtered)", "value": silent_str,         "inline": False},
            ],
            "footer": {"text": "Options Bot — no alert = nothing qualified"},
        }]
    }
    try:
        requests.post(webhook, json=payload, timeout=10)
    except Exception:
        pass


def _print_console_alert(data: dict, signal: dict, confidence: int, context: str) -> None:
    sep = "=" * 60
    print(f"\n{sep}")
    print(f"  ALERT: {data['ticker']}  —  {signal['label']}")
    print(f"  {signal['description']}")
    print(f"  Stock price : ${data['current_price']}")
    print(f"  Confidence  : {_confidence_bar(confidence)}")
    if context:
        print(f"  Context     : {context[:120]}...")
    print(f"{sep}\n")


# ── CSV logging ─────────────────────────────────────────────────────────────────

_CSV_HEADERS = [
    "timestamp", "ticker", "signal_type", "signal_label",
    "signal_value", "threshold_used", "price_at_alert",
    "put_call_ratio", "avg_iv", "total_volume",
    "top_contract", "confidence_score", "is_earnings_play",
    "data_source", "outcome",
]


def ensure_log_file() -> None:
    if not ALERTS_LOG.exists():
        with open(ALERTS_LOG, "w", newline="") as f:
            csv.DictWriter(f, fieldnames=_CSV_HEADERS).writeheader()
        log(f"Created alerts log at {ALERTS_LOG}")


def log_alert(data: dict, signal: dict, confidence: int, is_ep: bool) -> None:
    ensure_log_file()
    c_str = ""
    if data.get("top_contract"):
        c     = data["top_contract"]
        c_str = f"{c['type']} ${c['strike']} {c['expiry']} Vol:{c['volume']:,}"
    row = {
        "timestamp":        datetime.datetime.now(ET).strftime("%Y-%m-%d %H:%M:%S"),
        "ticker":           data["ticker"],
        "signal_type":      signal["type"],
        "signal_label":     signal["label"],
        "signal_value":     signal["value"],
        "threshold_used":   signal["threshold"],
        "price_at_alert":   data["current_price"],
        "put_call_ratio":   data["put_call_ratio"],
        "avg_iv":           data["avg_iv"],
        "total_volume":     data["total_volume"],
        "top_contract":     c_str,
        "confidence_score": confidence,
        "is_earnings_play": int(is_ep),
        "data_source":      data.get("data_source", "yfinance"),
        "outcome":          "",   # fill in: 1=hit, 0=miss
    }
    with open(ALERTS_LOG, "a", newline="") as f:
        csv.DictWriter(f, fieldnames=_CSV_HEADERS).writerow(row)


# ── Market hours ────────────────────────────────────────────────────────────────

def is_market_hours() -> bool:
    now = datetime.datetime.now(ET)
    if now.weekday() >= 5:
        return False
    open_  = now.replace(hour=9,  minute=30, second=0, microsecond=0)
    close_ = now.replace(hour=16, minute=0,  second=0, microsecond=0)
    return open_ <= now < close_


def is_pre_market_window() -> bool:
    now = datetime.datetime.now(ET)
    if now.weekday() >= 5:
        return False
    start = now.replace(hour=8,  minute=0,  second=0, microsecond=0)
    end   = now.replace(hour=9,  minute=25, second=0, microsecond=0)
    return start <= now < end


# ── Main scan ───────────────────────────────────────────────────────────────────

def run_scan() -> None:
    thresholds = load_thresholds()
    log(f"Scanning {len(config.TICKERS)} ticker(s): {', '.join(config.TICKERS)}")

    alerts_fired   = 0
    silent_reasons = []

    for ticker in config.TICKERS:
        log(f"  Checking {ticker} ...")
        data = fetch_options_data(ticker)
        if not data:
            silent_reasons.append(f"{ticker}: data unavailable")
            continue

        # Earnings check (done once per ticker)
        ep, ep_date      = is_earnings_play(ticker)
        near_earn, earn_date = earnings_in_next_week(ticker)
        earnings_soon    = ep  # true = earnings within 24h

        raw_signals = detect_raw_signals(data, thresholds)

        if not raw_signals:
            log(
                f"  {ticker}: no raw signals  "
                f"(PC={data['put_call_ratio']}, IV={data['avg_iv']}%, "
                f"Vol={data['total_volume']:,})"
            )
            continue

        for sig in raw_signals:
            if _is_duplicate(ticker, sig["type"]):
                log(f"  {ticker}: duplicate {sig['type']} suppressed")
                continue

            # Run all four gates
            passes, confidence, reason = check_all_gates(
                ticker        = ticker,
                signal_type   = sig["type"],
                volume_ratio  = sig.get("volume_ratio", 0),
                iv_change_pct = sig.get("iv_change"),
                pc_ratio      = sig.get("pc_ratio"),
                is_earnings_play = ep,
                has_earnings_soon = earnings_soon,
            )

            if not passes:
                log(f"  {ticker} [{sig['type']}] filtered — {reason}")
                silent_reasons.append(f"{ticker} {sig['type']}: {reason}")
                continue

            # All gates passed — fetch context (news + Reddit) only now
            log(f"  *** QUALIFIED SIGNAL: {ticker} — {sig['label']} (confidence {confidence}/100) ***")
            log(f"  Fetching news + sentiment for {ticker} ...")
            context = build_context_summary(ticker)

            # Fire alert
            send_discord_alert(data, sig, confidence, ep, ep_date or earn_date, context)
            log_alert(data, sig, confidence, ep)
            alerts_fired += 1

        time.sleep(1.5)

    if alerts_fired == 0:
        log(
            f"Scan complete — 0 alerts fired. "
            f"{len(silent_reasons)} signal(s) filtered out. "
            f"Silence = discipline."
        )
    else:
        log(f"Scan complete — {alerts_fired} alert(s) sent.")

    send_health_update(
        f"{'✅' if alerts_fired > 0 else '🔕'} "
        f"{alerts_fired} alert(s) fired — {len(silent_reasons)} filtered",
        alerts_fired,
        len(config.TICKERS),
        silent_reasons,
    )


def main() -> None:
    global _morning_analysis_done_date

    log("=" * 60)
    log("Options Alert Bot v2 — selective & disciplined")
    log(f"Tickers  : {', '.join(config.TICKERS)}")
    log(f"Interval : {config.SCAN_INTERVAL_MINUTES} min | market hours 9:30am–4pm ET")
    log("=" * 60)

    # Initialise data source (attempts Robinhood login)
    data_sources.init()
    ensure_log_file()

    if config.DISCORD_WEBHOOK_URL == "YOUR_DISCORD_WEBHOOK_URL_HERE":
        log("NOTE: Discord webhook not configured — alerts print to console", "WARN")

    while True:
        now       = datetime.datetime.now(ET)
        today_str = now.strftime("%Y-%m-%d")

        if is_pre_market_window() and _morning_analysis_done_date != today_str:
            try:
                from self_improve import run_morning_analysis
                run_morning_analysis()
                _morning_analysis_done_date = today_str
            except Exception as exc:
                log(f"Morning analysis failed: {exc}", "ERROR")

        if is_market_hours():
            try:
                run_scan()
            except Exception as exc:
                log(f"Scan error: {exc}", "ERROR")
                traceback.print_exc()
        else:
            log(
                f"Market closed ({now.strftime('%A %H:%M')} ET). "
                f"Next check in {config.SCAN_INTERVAL_MINUTES} min."
            )

        time.sleep(config.SCAN_INTERVAL_MINUTES * 60)


if __name__ == "__main__":
    main()
